// Datos de películas
const movies = [
  {
    id: 1,
    title: "Inception",
    image: "https://images.unsplash.com/photo-1653045474061-075ba29db54f?w=1920",
    rating: "98% Coincidencia",
    year: 2010,
    duration: "2h 28m",
    description: "Un ladrón que roba secretos corporativos mediante el uso de tecnología para compartir sueños recibe la tarea inversa de implantar una idea en la mente de un director ejecutivo.",
    genre: ["Sci-Fi", "Action", "Thriller"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page", "Tom Hardy"],
    director: "Christopher Nolan",
    imdbRating: 8.8,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 2,
    title: "The Dark Knight",
    image: "https://images.unsplash.com/photo-1765510296004-614b6cc204da?w=1920",
    rating: "99% Coincidencia",
    year: 2008,
    duration: "2h 32m",
    description: "Cuando la amenaza conocida como el Joker siembra el caos en la ciudad de Gotham, Batman debe afrontar una de las mayores pruebas psicológicas y físicas de su vida.",
    genre: ["Action", "Crime", "Drama"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    director: "Christopher Nolan",
    imdbRating: 9.0,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 3,
    title: "Interstellar",
    image: "https://images.unsplash.com/photo-1754638504964-880857928e64?w=1920",
    rating: "96% Coincidencia",
    year: 2014,
    duration: "2h 49m",
    description: "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento por asegurar la supervivencia de la humanidad.",
    genre: ["Sci-Fi", "Drama", "Adventure"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    director: "Christopher Nolan",
    imdbRating: 8.6,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 4,
    title: "Parasite",
    image: "https://images.unsplash.com/photo-1647575211406-ae6c9d4d2553?w=1920",
    rating: "97% Coincidencia",
    year: 2019,
    duration: "2h 12m",
    description: "La codicia y la desigualdad de clases amenazan la relación simbiótica entre la adinerada familia Park y la empobrecida familia Kim.",
    genre: ["Drama", "Thriller"],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    director: "Bong Joon-ho",
    imdbRating: 8.5,
    maturityRating: "R",
    language: "Coreano"
  },
  {
    id: 5,
    title: "The Shawshank Redemption",
    image: "https://images.unsplash.com/photo-1768693704768-a511d337e257?w=1920",
    rating: "99% Coincidencia",
    year: 1994,
    duration: "2h 22m",
    description: "Dos hombres presos entablan una amistad a lo largo de los años, encontrando consuelo y eventual redención a través de actos de decencia común.",
    genre: ["Drama"],
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    director: "Frank Darabont",
    imdbRating: 9.3,
    maturityRating: "R",
    language: "Inglés"
  },
  {
    id: 6,
    title: "The Godfather",
    image: "https://images.unsplash.com/photo-1767823608836-980209ad69ab?w=1920",
    rating: "98% Coincidencia",
    year: 1972,
    duration: "2h 55m",
    description: "El envejecido patriarca de una dinastía del crimen organizado transmite el control de su imperio clandestino a su renuente hijo.",
    genre: ["Crime", "Drama"],
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
    director: "Francis Ford Coppola",
    imdbRating: 9.2,
    maturityRating: "R",
    language: "Inglés"
  },
  {
    id: 7,
    title: "Pulp Fiction",
    image: "https://images.unsplash.com/photo-1595171694538-beb81da39d3e?w=1920",
    rating: "95% Coincidencia",
    year: 1994,
    duration: "2h 34m",
    description: "Las vidas de dos sicarios, un boxeador, un gánster y su esposa se entrelazan en cuatro relatos de violencia y redención.",
    genre: ["Crime", "Drama"],
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    director: "Quentin Tarantino",
    imdbRating: 8.9,
    maturityRating: "R",
    language: "Inglés"
  },
  {
    id: 8,
    title: "Fight Club",
    image: "https://images.unsplash.com/photo-1598472237441-b5422956195e?w=1920",
    rating: "94% Coincidencia",
    year: 1999,
    duration: "2h 19m",
    description: "Un oficinista insomne y un fabricante de jabón forman un club de lucha clandestino que evoluciona en algo mucho más grande.",
    genre: ["Drama", "Thriller"],
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
    director: "David Fincher",
    imdbRating: 8.8,
    maturityRating: "R",
    language: "Inglés"
  },
  {
    id: 9,
    title: "Forrest Gump",
    image: "https://images.unsplash.com/photo-1708787788824-07d6d97b0111?w=1920",
    rating: "96% Coincidencia",
    year: 1994,
    duration: "2h 22m",
    description: "Las presidencias de Kennedy y Johnson, la Guerra de Vietnam y otros acontecimientos históricos se desarrollan desde la perspectiva de un hombre de Alabama.",
    genre: ["Drama", "Romance"],
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    director: "Robert Zemeckis",
    imdbRating: 8.8,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 10,
    title: "The Matrix",
    image: "https://images.unsplash.com/photo-1761948245185-fc300ad20316?w=1920",
    rating: "97% Coincidencia",
    year: 1999,
    duration: "2h 16m",
    description: "Un hacker informático aprende de misteriosos rebeldes sobre la verdadera naturaleza de su realidad y su papel en la guerra contra sus controladores.",
    genre: ["Sci-Fi", "Action"],
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    director: "Lana Wachowski, Lilly Wachowski",
    imdbRating: 8.7,
    maturityRating: "R",
    language: "Inglés"
  }
];

function getTopRatedMovies() {
  return [...movies].sort((a, b) => b.imdbRating - a.imdbRating).slice(0, 10);
}
