// Datos de películas
const movies = [
  {
    id: 1,
    title: "Angels & Demons",
    image: "images/posters/angeles_y_demonios.jpg",
    rating: "98% Coincidencia",
    year: 2009,
    duration: "2h 18m",
    description: "El profesor Robert Langdon investiga una conspiración contra el Vaticano.",
    genre: ["Mystery", "Thriller"],
    cast: ["Tom Hanks", "Ewan McGregor"],
    director: "Ron Howard",
    imdbRating: 6.7,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 2,
    title: "Bohemian Rhapsody",
    image: "images/posters/bohemian_rhapsody.jpg",
    rating: "99% Coincidencia",
    year: 2018,
    duration: "2h 14m",
    description: "La historia de Freddie Mercury y la banda Queen.",
    genre: ["Biography", "Drama"],
    cast: ["Rami Malek", "Lucy Boynton"],
    director: "Bryan Singer",
    imdbRating: 7.9,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 3,
    title: "Bridgerton",
    image: "images/posters/bridgerton.webp",
    rating: "96% Coincidencia",
    year: 2020,
    duration: "Serie",
    description: "Drama romántico en la alta sociedad londinense.",
    genre: ["Drama", "Romance"],
    cast: ["Phoebe Dynevor", "Regé-Jean Page"],
    director: "Chris Van Dusen",
    imdbRating: 7.4,
    maturityRating: "TV-MA",
    language: "Inglés"
  },
  {
    id: 4,
    title: "Cars",
    image: "images/posters/cars.jpg",
    rating: "97% Coincidencia",
    year: 2006,
    duration: "1h 57m",
    description: "Un coche aprende el valor de la amistad.",
    genre: ["Animation", "Family"],
    cast: ["Owen Wilson", "Paul Newman"],
    director: "John Lasseter",
    imdbRating: 7.2,
    maturityRating: "G",
    language: "Inglés"
  },
  {
    id: 5,
    title: "El Señor de los Anillos: El Retorno del Rey",
    image: "images/posters/el_señor_de_los_anillos.jpg",
    rating: "99% Coincidencia",
    year: 2003,
    duration: "3h 21m",
    description: "La batalla final por la Tierra Media.",
    genre: ["Fantasy", "Adventure"],
    cast: ["Elijah Wood", "Viggo Mortensen"],
    director: "Peter Jackson",
    imdbRating: 9.0,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 6,
    title: "El último samurái",
    image: "images/posters/el_ultimo_samurai.webp",
    rating: "98% Coincidencia",
    year: 2003,
    duration: "2h 34m",
    description: "Un soldado aprende la cultura samurái.",
    genre: ["Action", "Drama"],
    cast: ["Tom Cruise", "Ken Watanabe"],
    director: "Edward Zwick",
    imdbRating: 7.8,
    maturityRating: "R",
    language: "Inglés"
  },
  {
    id: 7,
    title: "Fast & Furious",
    image: "images/posters/fast_and_furious.jpg",
    rating: "95% Coincidencia",
    year: 2001,
    duration: "1h 46m",
    description: "Carreras ilegales y robos en Los Ángeles.",
    genre: ["Action", "Crime"],
    cast: ["Vin Diesel", "Paul Walker"],
    director: "Rob Cohen",
    imdbRating: 6.8,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 8,
    title: "Frankenstein",
    image: "images/posters/frankenstein.webp",
    rating: "94% Coincidencia",
    year: 1994,
    duration: "2h 03m",
    description: "Un científico crea vida artificial con consecuencias trágicas.",
    genre: ["Horror", "Drama"],
    cast: ["Robert De Niro", "Kenneth Branagh"],
    director: "Kenneth Branagh",
    imdbRating: 6.4,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 9,
    title: "Hora de aventuras",
    image: "images/posters/hora_de_aventuras.jpg",
    rating: "96% Coincidencia",
    year: 2010,
    duration: "Serie",
    description: "Las aventuras de Finn y Jake en la Tierra de Ooo.",
    genre: ["Animation", "Adventure"],
    cast: ["Jeremy Shada", "John DiMaggio"],
    director: "Pendleton Ward",
    imdbRating: 8.6,
    maturityRating: "TV-PG",
    language: "Inglés"
  },
  {
    id: 10,
    title: "House",
    image: "images/posters/house.jpg",
    rating: "97% Coincidencia",
    year: 2004,
    duration: "Serie",
    description: "Un médico brillante pero antisocial resuelve casos complejos.",
    genre: ["Drama"],
    cast: ["Hugh Laurie"],
    director: "David Shore",
    imdbRating: 8.7,
    maturityRating: "TV-14",
    language: "Inglés"
  },
  {
    id: 11,
    title: "Juego de Tronos",
    image: "images/posters/juego_de_tronos.jpg",
    rating: "99% Coincidencia",
    year: 2011,
    duration: "Serie",
    description: "Familias nobles luchan por el control del Trono de Hierro.",
    genre: ["Fantasy", "Drama"],
    cast: ["Emilia Clarke", "Kit Harington"],
    director: "David Benioff, D.B. Weiss",
    imdbRating: 9.2,
    maturityRating: "TV-MA",
    language: "Inglés"
  },
  {
    id: 12,
    title: "La Casa de Papel",
    image: "images/posters/la_casa_de_papel.jpg",
    rating: "98% Coincidencia",
    year: 2017,
    duration: "Serie",
    description: "Un grupo realiza el mayor atraco de la historia.",
    genre: ["Crime", "Drama"],
    cast: ["Úrsula Corberó", "Álvaro Morte"],
    director: "Álex Pina",
    imdbRating: 8.2,
    maturityRating: "TV-MA",
    language: "Español"
  },
  {
    id: 13,
    title: "Los Mercenarios",
    image: "images/posters/los_mercenarios.jpg",
    rating: "95% Coincidencia",
    year: 2010,
    duration: "1h 43m",
    description: "Un grupo de mercenarios realiza misiones peligrosas.",
    genre: ["Action"],
    cast: ["Sylvester Stallone", "Jason Statham"],
    director: "Sylvester Stallone",
    imdbRating: 6.4,
    maturityRating: "R",
    language: "Inglés"
  },
  {
    id: 14,
    title: "Los Miserables",
    image: "images/posters/los_miserables.jpg",
    rating: "96% Coincidencia",
    year: 2012,
    duration: "2h 38m",
    description: "Historia de redención en la Francia del siglo XIX.",
    genre: ["Drama", "Musical"],
    cast: ["Hugh Jackman", "Russell Crowe"],
    director: "Tom Hooper",
    imdbRating: 7.6,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 15,
    title: "Orgullo y Prejuicio",
    image: "images/posters/pride_and_prejudice.jpg",
    rating: "97% Coincidencia",
    year: 2005,
    duration: "2h 09m",
    description: "Historia romántica basada en la novela de Jane Austen.",
    genre: ["Romance", "Drama"],
    cast: ["Keira Knightley", "Matthew Macfadyen"],
    director: "Joe Wright",
    imdbRating: 7.8,
    maturityRating: "PG",
    language: "Inglés"
  },
  {
    id: 16,
    title: "Shogun",
    image: "images/posters/shogun_poster.webp",
    rating: "98% Coincidencia",
    year: 2024,
    duration: "Serie",
    description: "Un marinero inglés llega al Japón feudal.",
    genre: ["Drama", "History"],
    cast: ["Hiroyuki Sanada"],
    director: "Justin Marks",
    imdbRating: 8.7,
    maturityRating: "TV-MA",
    language: "Japonés"
  },
  {
    id: 17,
    title: "Shrek 2",
    image: "images/posters/shrek_2.jpg",
    rating: "97% Coincidencia",
    year: 2004,
    duration: "1h 33m",
    description: "Shrek conoce a los padres de Fiona.",
    genre: ["Animation", "Comedy"],
    cast: ["Mike Myers", "Eddie Murphy"],
    director: "Andrew Adamson",
    imdbRating: 7.2,
    maturityRating: "PG",
    language: "Inglés"
  },
  {
    id: 18,
    title: "Spiderman",
    image: "images/posters/spiderman.jpg",
    rating: "98% Coincidencia",
    year: 2002,
    duration: "2h 01m",
    description: "Un joven obtiene poderes arácnidos.",
    genre: ["Action", "Adventure"],
    cast: ["Tobey Maguire", "Willem Dafoe"],
    director: "Sam Raimi",
    imdbRating: 7.4,
    maturityRating: "PG-13",
    language: "Inglés"
  },
  {
    id: 19,
    title: "The King",
    image: "images/posters/the_king.jpg",
    rating: "96% Coincidencia",
    year: 2019,
    duration: "2h 20m",
    description: "El ascenso del rey Enrique V de Inglaterra.",
    genre: ["Drama", "History"],
    cast: ["Timothée Chalamet", "Robert Pattinson"],
    director: "David Michôd",
    imdbRating: 7.3,
    maturityRating: "R",
    language: "Inglés"
  }
];

function getTopRatedMovies() {
  return [...movies].sort((a, b) => b.imdbRating - a.imdbRating).slice(0, 10);
}
